// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int largerThan = 0;
		int smallOrEqualTo = 0; 
		for (int count = 0; count < n; count++) {
			if (Math.random() > 0.5) {
				largerThan++;
			}
			else {
				smallOrEqualTo++;
			}
		}
        double ratio = (smallOrEqualTo > 0) ? (double) largerThan / smallOrEqualTo : 0.0;

		System.out.println("> 0.5: " + largerThan + " times");
		System.out.println("<= 0.5: " + smallOrEqualTo + " times");
		System.out.println("ratio: " + ratio);

	}
}
